source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'FastMovie' do
    pod 'Alamofire', '~> 4.5'
    pod 'RxSwift',    '~> 4.0'
    pod 'Kingfisher', '~> 4.0'
    pod 'SVProgressHUD'
end


